export const PURCHASES_CONFIG = {
  REVENUECAT_IOS_API_KEY: process.env.EXPO_PUBLIC_REVENUECAT_IOS_API_KEY || "",
  REVENUECAT_ANDROID_API_KEY: process.env.EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY || "",
  ENTITLEMENT_ID: "pro",
  PRODUCT_IDS: {
    IOS: "av1ate_lifetime_999",
    ANDROID: "av1ate_lifetime_999",
  },
  TRIAL_DAYS: 14,
  DEFAULT_PRICE: "$9.99",
};
